import requests
from fastapi import FastAPI, Depends, HTTPException
from sqlalchemy.orm import Session
import models, schemas
from database import engine, SessionLocal
import markdown

# This creates the physical notes.db file and tables when the app starts
models.Base.metadata.create_all(bind=engine)

app = FastAPI(title="Markdown Notes API")

# Dependency: Opens a database session for a request, then closes it when done
def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()

@app.get("/")
def read_root():
    return {"message": "Welcome to the Markdown Notes API 🚀"}

# Endpoint to create and save a new markdown note
@app.post("/notes/", response_model=schemas.NoteResponse)
def create_note(note: schemas.NoteCreate, db: Session = Depends(get_db)):
    # 1. Create the database object using the validated data
    db_note = models.Note(title=note.title, content=note.content)
    
    # 2. Add it to the database session
    db.add(db_note)
    
    # 3. Save (commit) the changes to the database
    db.commit()
    
    # 4. Refresh the object to get the new ID generated by the database
    db.refresh(db_note)
    
    return db_note

# Endpoint to list all saved notes
@app.get("/notes/", response_model=list[schemas.NoteResponse])
def read_notes(skip: int = 0, limit: int = 100, db: Session = Depends(get_db)):
    # Query the database for all notes
    notes = db.query(models.Note).offset(skip).limit(limit).all()
    return notes

# Endpoint to render a specific note as HTML
@app.get("/notes/{note_id}/html")
def render_note_html(note_id: int, db: Session = Depends(get_db)):
    # 1. Find the specific note by its ID
    db_note = db.query(models.Note).filter(models.Note.id == note_id).first()
    
    # 2. If the note doesn't exist, throw a 404 error
    if db_note is None:
        raise HTTPException(status_code=404, detail="Note not found")
    
    # 3. Convert the raw markdown content to HTML
    html_content = markdown.markdown(db_note.content)
    
    # 4. Return the HTML
    return {"id": db_note.id, "html_content": html_content}


# Endpoint to check the grammar of a saved note
@app.get("/notes/{note_id}/grammar")
def check_grammar(note_id: int, db: Session = Depends(get_db)):
    # 1. Fetch the specific note from your database
    db_note = db.query(models.Note).filter(models.Note.id == note_id).first()
    
    if db_note is None:
        raise HTTPException(status_code=404, detail="Note not found")
    
    # 2. Send the note's content to the LanguageTool API
    # We specify 'en-US' as the language we want to check against
    api_url = "https://api.languagetool.org/v2/check"
    data = {
        "text": db_note.content,
        "language": "en-US"
    }
    
    response = requests.post(api_url, data=data)
    
    # 3. Handle potential errors from the external API
    if response.status_code != 200:
        raise HTTPException(status_code=502, detail="Grammar checking service is currently unavailable")
        
    # 4. Return the grammar suggestions to the user
    return response.json()